Milestone: Restaurant Page
newhorizon-tech/minimalist-restaurant-page pull request #1
Opened 2021-03-02 13:51 UTC by newhorizon-tech

Concepts used in the project: 

- DOM manipulation 
- ES6 Modules 
- ES6 Functions 
- Bundling Modules  
- Asset Management

2021-03-02 17:02 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @newhorizon-tech! 👋 
You have done an amazing job with this project!! 🤩  It looks good, works well and embedding the map was a great choice 🏆 There are just a few issues that need to be resolved before you can move on: ⬇️ 

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-03-02 17:02 UTC, BrittanyBlake commented on package.json
> +  },
- [x] You are missing the necessary run common commands like `build` and `development`. 
screenshot from pathwright 👇🏾 
![Screen Shot 2021-03-02 at 5 56 43 PM](https://user-images.githubusercontent.com/48804258/109684537-a4739280-7b80-11eb-833e-95eb87d39083.png)
```suggestion
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2021-03-03 02:27 UTC, newhorizon-tech commented
Added common commands (dev, build, start) to package.json

2021-03-03 02:47 UTC, arslanbisharat approved these changes
# Approved 🥇 

Thank you for submitting this project. You have done a great job!

- [x] You have a descriptive Pull Request 👏 
- [x] You have a descriptive Readme. 👏 
- [x] Your commit messages are very descriptive too. I am very happy to see that.  👏 
- [x] No Linter error found. 👏 
- [x] Met Min. requirements. 

I am very happy to review your project. Looking forward to amazing new projects from your side. 

**Best,
Arslan Bisharat**
_You can always contact me on slack at @arslanbisharat 📞_

2021-03-03 03:11 UTC, merged